# Generated by Django 5.2 on 2025-04-20 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_is_active_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age_suitability',
            field=models.CharField(choices=[('0-5 months', '0-5 months'), ('6-11 months', '6-11 months'), ('1-1.5 years', '1-1.5 years'), ('1.6-2 years', '1.6-2 years'), ('3-5 years', '3-5 years'), ('6-8 years', '6-8 years'), ('9-12 years', '9-12 years'), ('mothers', 'mothers')], default='0-5 months', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='durability',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='product',
            name='educational_value',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], default='Unisex', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='giftability',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='product',
            name='safety_perception',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='product',
            name='seasonal_use',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='value_for_money',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
