# Generated by Django 5.2 on 2025-05-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_chemical_safety_product_design_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age_suitability',
            field=models.CharField(choices=[('0-5 months', '0-5 months'), ('6-11 months', '6-11 months'), ('1-1.5 years', '1-1.5 years'), ('1.6-2 years', '1.6-2 years'), ('3-5 years', '3-5 years'), ('6-8 years', '6-8 years'), ('9-12 years', '9-12 years'), ('mothers', 'mothers'), ('all ages', 'all ages')], default='0-5 months', max_length=20),
        ),
    ]
